### ISSUE TITLE
ON/OFF turns on and off all relays.

### ISSUE THREAD

**Issue by duelago** [birdslikewires/hubitat#22]
Data window in Hubitat:

endpointId: 01
application: 46
driver: v1.10 (29th August 2023)
inClusters: 0000,0003,0004,0005,0006
manufacturer: _TZ3000_1obwwnmq
model: TS011F
outClusters: 0019,000A
profileId: 0104

Debug from Hubitat:

[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:34.207[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:34.198[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:34.189[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:34.174[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:29.750[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:29.745[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:29.742[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:58:29.712[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:56:21.050[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 8079 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:54:26.918[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:52:21.029[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 7839 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:48:21.037[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 7599 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:44:21.755[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:44:21.029[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 7359 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:40:21.032[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 7119 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:36:21.052[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 6879 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:34:16.638[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:32:21.046[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 6639 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:28:21.044[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 6399 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:24:21.023[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 6159 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:24:11.448[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:20:21.033[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 5919 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:16:21.046[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 5679 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:14:06.306[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:12:21.027[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 5439 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:08:21.043[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 5199 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:04:21.025[warn](http://192.168.7.63/logs?tab=past&deviceId=702#)Outlet : Health Status : Last report received 4959 seconds ago.
[dev:702](http://192.168.7.63/logs?tab=past&deviceId=702#)2023-10-13 14:04:01.180[error](http://192.168.7.63/logs?tab=past&deviceId=702#)com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Switch' in namespace 'hubitat' not found on line 782 (method parse)

**Comment by andydvsn** [comment]
Think this should be fixed in the last update, there was something [very odd happening with a for loop](https://github.com/birdslikewires/hubitat/commit/0ccada2dca1b8ec2921c170d93aaaa50acd00a11) of all things.

**Comment by duelago** [comment]
> Think this should be fixed in the last update, there was something [very odd happening with a for loop](https://github.com/birdslikewires/hubitat/commit/0ccada2dca1b8ec2921c170d93aaaa50acd00a11) of all things.
![Screenshot 2023-12-07 at 14 58 29](https://github.com/birdslikewires/hubitat/assets/12539239/853fa20a-5c39-498c-be21-4fbbab3ebb71)

Thanks! It looks correct now. I can see the three different relays, but turning off one is still turning off all. Need to do some more testing. 

I will report back in a few days

**Comment by duelago** [comment]
I'm afraid it is still not working. The log below. Nothing happens if I toggle a relay with Lidl Smart Extension driver.
I am running v1.11 (25th November 2023)

All relays toggle if I set the driver to generic switch, even if I click relay 01, 02 or 03 individually.
I also tested to set Lidl Smart Plug as the driver, but nothing happens 


023-12-09 05:44:04.062 PM[warn](http://192.168.8.21/logs?tab=past&deviceId=7#)01 : Health Status : Waiting for first report.
[dev:7](http://192.168.8.21/logs?tab=past&deviceId=7#)2023-12-09 05:41:09.482 PM[error](http://192.168.8.21/logs?tab=past&deviceId=7#)groovy.lang.MissingMethodException: No signature of method: user_driver_BirdsLikeWires_Lidl_Smart_Extension_606.parse() is applicable for argument types: (java.util.ArrayList) values: [[[name:switch, value:on]]]
Possible solutions: parse(java.lang.String), push(java.lang.Object), use([Ljava.lang.Object;), wait(), run(), ping() on line 162 (method parse)
[dev:7](http://192.168.8.21/logs?tab=past&deviceId=7#)2023-12-09 05:41:09.393 PM[error](http://192.168.8.21/logs?tab=past&deviceId=7#)groovy.lang.MissingMethodException: No signature of method: user_driver_BirdsLikeWires_Lidl_Smart_Extension_606.parse() is applicable for argument types: (java.util.ArrayList) values: [[[name:switch, value:on]]]
Possible solutions: parse(java.lang.String), push(java.lang.Object), use([Ljava.lang.Object;), wait(), run(), ping() on line 197 (method parse)

![Screenshot 2023-12-09 at 17 33 44](https://github.com/birdslikewires/hubitat/assets/12539239/d5ae3679-ab64-465e-88e0-d99618521741)

**Comment by andydvsn** [comment]
The latest version is v1.13 from 7th December, could you try updating with HPM and giving it another try?

**Comment by duelago** [comment]
> The latest version is v1.13 from 7th December, could you try updating with HPM and giving it another try?
> 
> Both the driver and the general library will need updating and it's easiest done with HPM.

It works!!! Great job.
I had to remove the old drivers and pair the extension cord again to get it up and running. 

Thank you!
